const cartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    CART_ADD_ITEMS: 'CART_ADD_ITEMS',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    CLEAR_CART: 'CLEAR_CART',
};

export default cartActionTypes;